# Generated by Django 3.0.7 on 2020-10-30 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion de la Ficha')),
                ('title', models.CharField(max_length=40, verbose_name='Titulo de la Ficha')),
                ('max_persons', models.PositiveIntegerField(default=1, verbose_name='Maximo personas')),
                ('bedrooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dormitorios')),
                ('beds', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Camas')),
                ('bathrooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Baños')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('Se admiten mascotas', 'Admiten mascotas'), ('Lugar de estacionamiento privado', 'Estacionamiento privado'), ('Lugar de estacionamiento gratuito techado', 'Estacionamiento gratuito techado'), ('Lugar de estacionamiento gratuito a la calle', 'Estacionamiento gratuito a la calle'), ('Internet', 'Internet'), ('Apto para familias y niños', 'Familias y niños'), ('Televisor', 'Televisor'), ('Elementos basicos para la playa', 'Elementos de playa'), ('Lavarropas', 'Lavarropas'), ('Servicios básicos de higiene', 'Servicios básicos de higiene'), ('Agua caliente', 'Agua caliente'), ('Aire acondicionado', 'Aire acondicionado'), ('Calefacción', 'Calefacción'), ('Elementos de cocina basicos', 'Cocina basica'), ('Microondas', 'Microondas'), ('Desayuno incluido', 'Desayuno incluido'), ('Patio trasero', 'Patio trasero'), ('Patio delantero', 'Patio delantero'), ('Balcón', 'Balcón'), ('Parrilla', 'Parrilla'), ('Frente a la playa', 'Frente a la playa'), ('A pocas cuadras de la playa', 'Cercano a la playa'), ('Botiquin', 'Botiquin'), ('Alarma', 'Alarma'), ('Detector de humo', 'Detector de humo'), ('Detector de monoxido de carbono', 'Detector monoxido de carbono'), ('Barrio privado', 'Barrio privado')], default='No tiene servicios', max_length=531)),
                ('category', models.CharField(choices=[('Bungaló', 'Bungaló'), ('Cabaña', 'Cabaña'), ('Casa Comunal', 'Casa Comunal'), ('Casa de Huéspedes', 'Casa de Huéspedes'), ('Casa Entera', 'Casa Entera'), ('Chalé', 'Chalé'), ('Departamento', 'Departamento'), ('Duplex', 'Duplex'), ('Loft', 'Loft'), ('Mansión', 'Mansión'), ('Villa Residencial', 'Villa Residencial')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='Usuario que reservó')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(max_length=50, null=True, verbose_name='El codigo de la reserva')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostapp.Property')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='1998-7-27', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostapp.Property')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostapp.Reservation')),
            ],
        ),
    ]
