# Generated by Django 2.2.1 on 2020-10-23 13:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion de la Ficha')),
                ('title', models.CharField(max_length=20, verbose_name='Titulo de la Ficha')),
                ('max_persons', models.PositiveIntegerField(verbose_name='Maximo personas')),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dormitorios')),
                ('beds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Baños')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.CharField(choices=[('HAB PRIV', 'Habitación Privada'), ('CA ENT', 'Casa Entera')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostapp.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
