# Generated by Django 3.0.7 on 2020-10-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostapp.Reservation'),
        ),
    ]
