# Generated by Django 2.2.1 on 2020-10-23 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dormitorios'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Camas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximo personas'),
        ),
    ]
