# Generated by Django 2.2.1 on 2020-10-25 22:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0002_auto_20201023_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('this gets stored in your database', 'This item is what you see in the drop-down'), ('Se admiten mascotas', 'Admiten mascotas'), ('Lugar de estacionamiento privado', 'Estacionamiento privado'), ('Internet', 'Internet'), ('Apto para familias y niños', 'Familias y niños')], default='No tiene servicios', max_length=122),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.CharField(max_length=30, verbose_name='Usuario que reservó'),
        ),
        migrations.AddField(
            model_name='reservationdate',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostapp.Property'),
        ),
        migrations.AddField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostapp.Reservation'),
        ),
    ]
