# Generated by Django 2.2.1 on 2020-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0002_auto_20201030_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='mail@prueba.com', max_length=254, verbose_name='Email del usuario'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='userFirstName',
            field=models.CharField(default='nombre', max_length=30, verbose_name='Nombre del usuario que reservó'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='userLastName',
            field=models.CharField(default='apellido', max_length=30, verbose_name='Apellido del usuario que reservó'),
        ),
    ]
