# Generated by Django 2.2.1 on 2020-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0003_auto_20201029_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Titulo de la Ficha'),
        ),
    ]
