# Generated by Django 2.2.1 on 2020-10-25 22:53

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0003_auto_20201025_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdate',
            name='date',
            field=models.DateField(default="1998-7-27"),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Numeros enteros en lo posible', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio por dia'),
        ),
        migrations.AlterField(
            model_name='property',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Se admiten mascotas', 'Admiten mascotas'), ('Lugar de estacionamiento privado', 'Estacionamiento privado'), ('Internet', 'Internet'), ('Apto para familias y niños', 'Familias y niños')], default='No tiene servicios', max_length=88),
        ),
    ]
