# Generated by Django 2.2.1 on 2020-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0004_auto_20201025_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdate',
            name='code',
            field=models.CharField(max_length=50, null=True, verbose_name='El codigo de la reserva'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='date',
            field=models.DateField(default='1998-7-27', null=True),
        ),
    ]
