# Generated by Django 2.2.1 on 2020-10-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0004_auto_20201030_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostapp.Reservation'),
        ),
    ]
