# Generated by Django 2.2.1 on 2020-10-28 00:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0005_auto_20201027_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Bungaló', 'Bungaló'), ('Cabaña', 'Cabaña'), ('Casa Comunal', 'Casa Comunal'), ('Casa de Huéspedes', 'Casa de Huéspedes'), ('Casa Entera', 'Casa Entera'), ('Chalé', 'Chalé'), ('Departamento', 'Departamento'), ('Duplex', 'Duplex'), ('Loft', 'Loft'), ('Mansión', 'Mansión'), ('Villa Residencial', 'Villa Residencial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Se admiten mascotas', 'Admiten mascotas'), ('Lugar de estacionamiento privado', 'Estacionamiento privado'), ('Lugar de estacionamiento gratuito techado', 'Estacionamiento gratuito techado'), ('Lugar de estacionamiento gratuito a la calle', 'Estacionamiento gratuito a la calle'), ('Internet', 'Internet'), ('Apto para familias y niños', 'Familias y niños'), ('Televisor', 'Televisor'), ('Elementos basicos para la playa', 'Elementos de playa'), ('Lavarropas', 'Lavarropas'), ('Servicios básicos de higiene', 'Servicios básicos de higiene'), ('Agua caliente', 'Agua caliente'), ('Aire acondicionado', 'Aire acondicionado'), ('Calefacción', 'Calefacción'), ('Elementos de cocina basicos', 'Cocina basica'), ('Microondas', 'Microondas'), ('Desayuno incluido', 'Desayuno incluido'), ('Patio trasero', 'Patio trasero'), ('Patio delantero', 'Patio delantero'), ('Balcón', 'Balcón'), ('Parrilla', 'Parrilla'), ('Frente a la playa', 'Frente a la playa'), ('A pocas cuadras de la playa', 'Cercano a la playa'), ('Botiquin', 'Botiquin'), ('Alarma', 'Alarma'), ('Detector de humo', 'Detector de humo'), ('Detector de monoxido de carbono', 'Detector monoxido de carbono'), ('Barrio privado', 'Barrio privado')], default='No tiene servicios', max_length=531),
        ),
    ]
