# Generated by Django 2.2.1 on 2020-10-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0008_auto_20201030_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(default='2020-10-31', null=True),
        ),
    ]
