# Generated by Django 2.2.1 on 2020-10-31 04:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0009_reservation_date_of_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='reservation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostapp.Reservation'),
        ),
    ]
