# Generated by Django 2.2.1 on 2020-10-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0010_auto_20201031_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo de la Ficha'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userFirstName',
            field=models.CharField(default='nombre', max_length=50, verbose_name='Nombre del usuario que reservó'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userLastName',
            field=models.CharField(default='apellido', max_length=50, verbose_name='Apellido del usuario que reservó'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='date',
            field=models.DateField(default='2020-10-31', null=True),
        ),
    ]
